#!/bin/bash
# these passwords are for LDAP manager itself. Once run it will be hosted on localhost:8080
docker run \
-p 8080:80  -d \
--name lam \
-e LDAP_SERVER=ldap://ldap.platformfeverdream.io \
-e LDAP_ADMIN_PASSWORD='demopassword' \
-e LDAP_DOMAIN='platformfeverdream.io' \
-e LAM_PASSWORD='demopassword' \
ldapaccountmanager/lam:stable